### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by rathorology** [kearnz/autoimpute#26]
Trying to install it by
pip install autoimpute
ERROR: Could not find a version that satisfies the requirement autoimpute (from versions: none)
ERROR: No matching distribution found for autoimpute

**Comment by kearnz** [comment]
Hi, 

Unfortunately, I am unable to recreate this issue. I was able to successfully install autoimpute both globally (using `pip install autoimpute`) and in a virtual environment, using the code below:

```python
cd ~/Desktop
virtualenv imp
source imp/bin/activate
pip install autoimpute
```

Note that I am using a macOS High Sierra 10.13.6, and I use Anaconda distribution with python 3.6.

Do you have any more information to provide? Are you able to `pip install` other packages? I've found this [thread](https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies) that may be able to help.

Please let me know if you have any other questions or issues that I can help debug.

**Comment by kearnz** [comment]
Closed because no further conversation. Feel free to reopen if issues persist.

**Comment by rathorology** [comment]
This is the error I am getting while installing it through pip install
autoimpute:
ERROR: Could not find a version that satisfies the requirement autoimpute
(from versions: none)
ERROR: No matching distribution found for autoimpute
