### ISSUE TITLE
Adding convergence criterion and monitoring to MiceImputer

### ISSUE THREAD

**Issue by maxmahlke** [kearnz/autoimpute#55]
**Problem**

The `MiceImputer` accepts a keyword `k` for the number of iterations. There is no easy way of determining the optimal `k` depending on the data at hand.

Currently, I am fixing the imputation with a `seed` while increasing `k` to monitor the convergence of the imputed variables. This is code-wise ok but computationally very inefficient.

**Possible Solutions**

I see two solutions which could both be implemented:

- Adding a convergence/stopping criterion based on the elements of the difference matrix between iterations. This would be a keyword of the `MiceImputer` constructor
- Caching the imputation results between iterations and creating a `plot_convergence` function which displays the change of imputed variables over the iterations, as in Figures 7-10 in [Buuren+ 2011](https://www.jstatsoft.org/article/view/v045i03), or  [here](https://stefvanbuuren.name/fimd/fig/ch6-convergence1-1.png).

**Alternative to new feature**

A less user-friendly but more exhaustive solution would be to _optionally_ return all iteration results for each imputation run, not just the final one. Assuming I'm instantiating `MiceImputer` with `k=10`, `n=5`, and `return_list=True,` I would then be getting a list with 5 elements (just as now), where each element is itself a list with 10 elements, each element being the data matrix at various imputation steps.

----

I have not seen this being addressed in any branch of the code. I'm also not very familiar with MICE, so maybe there is a better way of determining `k` that I'm not aware of. If you think this feature could be valuable, I'd be happy to contribute code in  any part you see fit.

**Comment by maxmahlke** [comment]
Hi Joe, 

apologies for the delay. For context, I'm interested in imputation as part of my PhD research. This week I further looked into the Maximum Likelihood + EM algorithm approach as an alternative, and I will explore that direction for now as the MiceImputer in combination with Bayesian Regression is quite expensive computationally (dataframe is 280,000 x 75 with missing values in each feature). If I get back to imputation, I will gladly contribute to this project!

Cheers
Max

**Comment by kearnz** [comment]
Hi Max,

Sounds good, and good luck with your research! Would be interested to hear what you find with ML + EM. I wanted to add those approaches to autoimpute but didn't have time in the first major release. Would love to collaborate on that as well if you'd like to contribute in that way at any point in the future.

Best,
Joe
