### ISSUE TITLE
Strategy parameter not included in documentation

### ISSUE THREAD

**Issue by nirtiac** [kearnz/autoimpute#61]
The strategy parameter is not documented in key functions such as MultipleImputer. This sadly has been making it difficult for me to figure out how (and if) I can use this package for mixed-type imputation including with categorical features one-hot encoded.

**Comment by kearnz** [comment]
Hi @nirtiac,

Thanks for bringing this to my attention. The parameters _should_ be autogenerated, and I had not noticed that the `strategy` parameter is missing. Let me look into this - should have a fix by the end of the week. Will leave the issue open until then.

Joe

**Comment by kearnz** [comment]
Hi @nirtiac,

I added the `strategy` param to the docstrings for each imputer. I also added the `BaseImputer` to the docs, which contains all the strategies. Still fidgeting with the docstring formatting for autogenerating docs, so bear with me there, but hopefully the content is at least helpful. 

For the cleanest view on the strategies, you may want to look at the [BaseImputer](https://github.com/kearnz/autoimpute/blob/master/autoimpute/imputations/dataframe/base_imputer.py) itself, followed by the [folder](https://github.com/kearnz/autoimpute/tree/master/autoimpute/imputations/series) that contains each strategy.

Closing for now, but feel free to re open if any other issues

**Comment by nirtiac** [comment]
Thank you @kearnz!! Much appreciated!
