### ISSUE TITLE
mice example with mixed data types

### ISSUE THREAD

**Issue by chanshing** [kearnz/autoimpute#63]
Does the MICE imputer handle mixed categorical & continuous types automatically? I can't make it work and I can't find an example in the tutorials.

**Comment by kearnz** [comment]
Hi @chanshing - MICE (and autoimpute) generally work with categorical variables, although the support for numerical variables is much more mature. What exactly are you trying to do? impute a categorical variable? Pass it as a predictor for other columns? If you can post traceback or error logs or some more detail.

**Comment by kearnz** [comment]
closing this as discussion ended - feel free to reopen if you still have further questions!

**Comment by kauttoj** [comment]
Hi. I have the same question. Could you take a look of my simple example and tell me how should I use MICE for mixed data?

```
import numpy as np
import pandas as pd

# create some dummy data
data = pd.DataFrame({'A':np.random.rand(20), 'B': np.random.choice(['#','%','¤'],size=20), 'C': np.random.rand(20)})
data['A'] = data['A'].astype(float)
data['C'] = data['C'].astype(float)
data['B'] = data['B'].astype('category')

# add some missing elements
data.iloc[5,0] = np.nan
data.iloc[10,0]=np.nan
data.iloc[10,1]=np.nan
data.iloc[11,1]=np.nan
data.iloc[12,2]=np.nan
data.iloc[15,2] =np.nan

# try with defaults
mice = MiceImputer(return_list=True)
new_data = mice.fit_transform(data) # FAILED

# try with some specified strategy
strategy = {'A': 'default predictive','C': 'default predictive','B':'multinomial logistic'}
mice = MiceImputer(strategy=strategy,return_list=True)
new_data = mice.fit_transform(data) # FAILED
```
Both fail with "ValueError: Unable to convert array of bytes/strings into decimal numbers with dtype='numeric'"
