### ISSUE TITLE
imp_kwgs index in docs?

### ISSUE THREAD

**Issue by nick-youngblut** [kearnz/autoimpute#71]
At least from reading the part II tutorial, I don't see how one is supposed to know all of the possible `imp_kwgs` for each strategy and what each parameter does. It would help to have a webpage listing this info (eg., `Tutorials => imp_kwgs index`)

**Comment by kearnz** [comment]
looking to update the tutorials in the next few weeks! apologies for the delay on this. good suggestion will keep note
