### ISSUE TITLE
Fix for sklearn 1.0, regarding the initialisation error

### ISSUE THREAD

**Issue by bramiozo** [kearnz/autoimpute#73]
In imputations.series lrd and pmm the following should be changed in the __init__ to fix the initialisation errors

Now  it has 
```
self.lm = LinearRegression(
            self.fit_intercept,
            self.normalize,
            self.copy_x,
            self.n_jobs,
        )
```
but it should be

```
self.lm = LinearRegression(
            fit_intercept=self.fit_intercept,
            normalize=self.normalize,
            copy_X=self.copy_x,
            n_jobs=self.n_jobs,
        )
```

Note: I did no rigorous check to verify these are the only locations where this init takes place.

Thanks for this very useful library :))

**Comment by kearnz** [comment]
Great, this may be the init issue causing errors in a few other issues, so going to test shortly and deploy a fix.

Glad the repository is helpful for you!

**Comment by kearnz** [comment]
made these changes and tested w/ github actions. All tests passed (although there are some warnings). Let me know if good to go on your end. Closing the issue for now but feel free to reopen!
