### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by Jacer7** [kearnz/autoimpute#87]
# simple example using default instance of MiceImputer
imp = MiceImputer()

# fit transform returns a generator by default, calculating each imputation method lazily
imp.fit_transform(data)

As the np.object has been depreciated from the version 1.19.0 , while fitting data and transforming it, it shows the error as module 'numpy' has no attribute 'object'.

**Comment by kearnz** [comment]
thanks for flagging. I'll get version dependencies up to speed & resolved this week.

**Comment by kearnz** [comment]
code is updated, so I'll close this now. you can get the latest by git cloning the repo. I'll release a new version (0.13.1) shortly.
