### ISSUE TITLE
error: np.object` was a deprecated alias for the builtin `object

### ISSUE THREAD

**Issue by AAbou-foul** [kearnz/autoimpute#89]
Dear all,
Any proposed updates to fix numpy compatibility issue with autoimpute?

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20

**Comment by kearnz** [comment]
Hi - I've actually updated the compatibility issue already but have not released a new version, as the update is causing another unit test to fail. Will look to have this resolved asap.

**Comment by kearnz** [comment]
this is finally fixed w/ a new version `0.14.1`
